[workspace]
resolver = "2"
members = [
    "crates/digtrax",
    "crates/digtrax-ui",
    "crates/digtrax-cli",
    "crates/digtrax-tag",
    "crates/digtrax-shared",
    "crates/digtrax-player",
    "crates/digtrax-tagger",
    "crates/digtrax-renamer",
    "crates/digtrax-autotag",
    "crates/digtrax-playlist",
    "crates/digtrax-platforms"
]

# Workaround for MacOS
[workspace.dependencies]
lzma-sys = { version = "*", features = ["static"] }

[profile.release]
opt-level = 3
